--Parteien einfügen
INSERT INTO Partei VALUES (1, "Volksabst.", "Ab jetzt...Bündnis für Deutschland, für Demokratie durch Volksabstimmung ");
INSERT INTO Partei VALUES (2, "ADM", "Allianz der Mitte ");
INSERT INTO Partei VALUES (3, "BP", "Bayernpartei ");
INSERT INTO Partei VALUES (4, "GRÜNE", "BÜNDNIS 90/DIE GRÜNEN ");
INSERT INTO Partei VALUES (5, "BüSo", "Bürgerrechtsbewegung Solidarität ");
INSERT INTO Partei VALUES (6, "CDU", "Christlich Demokratische Union Deutschlands ");
INSERT INTO Partei VALUES (7, "CM", "CHRISTLICHE MITTE - Für ein Deutschland nach GOTTES Geboten ");
INSERT INTO Partei VALUES (8, "CSU", "Christlich-Soziale Union in Bayern e.V. ");
INSERT INTO Partei VALUES (9, "DVD", "Demokratische Volkspartei Deutschland ");
INSERT INTO Partei VALUES (10, "DKP", "Deutsche Kommunistische Partei ");
INSERT INTO Partei VALUES (11, "DVU", "DEUTSCHE VOLKSUNION ");
INSERT INTO Partei VALUES (12, "ZENTRUM", "Deutsche Zentrumspartei - Älteste Partei Deutschlands gegründet 1870 ");
INSERT INTO Partei VALUES (13, "DIE LINKE", "DIE LINKE ");
INSERT INTO Partei VALUES (14, "REP", "DIE REPUBLIKANER ");
INSERT INTO Partei VALUES (15, "VIOLETTEN", "Die Violetten");
INSERT INTO Partei VALUES (16, "FAMILIE", "Familien-Partei Deutschlands ");
INSERT INTO Partei VALUES (17, "FDP", "Freie Demokratische Partei ");
INSERT INTO Partei VALUES (18, "Freie Union", "Freie Union ");
INSERT INTO Partei VALUES (19, "FWD", "Freie Wähler Deutschland ");
INSERT INTO Partei VALUES (20, "MLPD", "Marxistisch-Leninistische Partei Deutschlands ");
INSERT INTO Partei VALUES (21, "Tierschutz", "Mensch Umwelt Tierschutz ");
INSERT INTO Partei VALUES (22, "NPD", "Nationaldemokratische Partei Deutschlands ");
INSERT INTO Partei VALUES (23, "ödp", "Ökologisch-Demokratische Partei ");
INSERT INTO Partei VALUES (24, "PBC", "Partei Bibeltreuer Christen ");
INSERT INTO Partei VALUES (25, "PSG", "Partei für Soziale Gleichheit, Sektion der Vierten Internationale ");
INSERT INTO Partei VALUES (26, "PIRATEN", "Piratenpartei Deutschland  ");
INSERT INTO Partei VALUES (27, "RRP", "Rentnerinnen und Rentner Partei ");
INSERT INTO Partei VALUES (28, "RENTNER", "Rentner-Partei-Deutschland ");
INSERT INTO Partei VALUES (29, "SPD", "Sozialdemokratische Partei Deutschlands ");
INSERT INTO Partei VALUES (30, "Parteilose", "Parteilose");