INSERT INTO Wahlkreis VALUES(1, "Flensburg - Schleswig", 15)
INSERT INTO Wahlkreis VALUES(2, "Nordfriesland - Dithmarschen Nord", 15)
INSERT INTO Wahlkreis VALUES(3, "Steinburg - Dithmarschen Süd", 15)
INSERT INTO Wahlkreis VALUES(4, "Rendsburg-Eckernförde", 15)
INSERT INTO Wahlkreis VALUES(5, "Kiel", 15)
INSERT INTO Wahlkreis VALUES(6, "Plön - Neumünster", 15)
INSERT INTO Wahlkreis VALUES(7, "Pinneberg", 15)
INSERT INTO Wahlkreis VALUES(8, "Segeberg - Stormarn-Nord", 15)
INSERT INTO Wahlkreis VALUES(9, "Ostholstein", 15)
INSERT INTO Wahlkreis VALUES(10, "Herzogtum Lauenburg - Stormarn-Süd", 15)
INSERT INTO Wahlkreis VALUES(11, "Lübeck", 15)
INSERT INTO Wahlkreis VALUES(12, "Wismar - Nordwestmecklenburg - Parchim", 8)
INSERT INTO Wahlkreis VALUES(13, "Schwerin - Ludwigslust", 8)
INSERT INTO Wahlkreis VALUES(14, "Rostock", 8)
INSERT INTO Wahlkreis VALUES(15, "Stralsund - Nordvorpommern - Rügen", 8)
INSERT INTO Wahlkreis VALUES(16, "Greifswald - Demmin - Ostvorpommern", 8)
INSERT INTO Wahlkreis VALUES(17, "Bad Doberan - Güstrow - Müritz", 8)
INSERT INTO Wahlkreis VALUES(18, "Neubrandenburg - Mecklenburg-Strelitz - Uecker-Randow", 8)
INSERT INTO Wahlkreis VALUES(19, "Hamburg-Mitte", 6)
INSERT INTO Wahlkreis VALUES(20, "Hamburg-Altona", 6)
INSERT INTO Wahlkreis VALUES(21, "Hamburg-Eimsbüttel", 6)
INSERT INTO Wahlkreis VALUES(22, "Hamburg-Nord", 6)
INSERT INTO Wahlkreis VALUES(23, "Hamburg-Wandsbek", 6)
INSERT INTO Wahlkreis VALUES(24, "Hamburg-Bergedorf - Harburg", 6)
INSERT INTO Wahlkreis VALUES(25, "Aurich - Emden", 9)
INSERT INTO Wahlkreis VALUES(26, "Unterems", 9)
INSERT INTO Wahlkreis VALUES(27, "Friesland - Wilhelmshaven", 9)
INSERT INTO Wahlkreis VALUES(28, "Oldenburg - Ammerland", 9)
INSERT INTO Wahlkreis VALUES(29, "Delmenhorst - Wesermarsch - Oldenburg-Land", 9)
INSERT INTO Wahlkreis VALUES(30, "Cuxhaven - Stade II", 9)
INSERT INTO Wahlkreis VALUES(31, "Stade I - Rotenburg II", 9)
INSERT INTO Wahlkreis VALUES(32, "Mittelems", 9)
INSERT INTO Wahlkreis VALUES(33, "Cloppenburg - Vechta", 9)
INSERT INTO Wahlkreis VALUES(34, "Diepholz - Nienburg I", 9)
INSERT INTO Wahlkreis VALUES(35, "Osterholz - Verden", 9)
INSERT INTO Wahlkreis VALUES(36, "Rotenburg I - Soltau-Fallingbostel", 9)
INSERT INTO Wahlkreis VALUES(37, "Harburg", 9)
INSERT INTO Wahlkreis VALUES(38, "Lüchow-Dannenberg - Lüneburg", 9)
INSERT INTO Wahlkreis VALUES(39, "Osnabrück-Land", 9)
INSERT INTO Wahlkreis VALUES(40, "Stadt Osnabrück", 9)
INSERT INTO Wahlkreis VALUES(41, "Nienburg II - Schaumburg", 9)
INSERT INTO Wahlkreis VALUES(42, "Stadt Hannover I", 9)
INSERT INTO Wahlkreis VALUES(43, "Stadt Hannover II", 9)
INSERT INTO Wahlkreis VALUES(44, "Hannover-Land I", 9)
INSERT INTO Wahlkreis VALUES(45, "Celle - Uelzen", 9)
INSERT INTO Wahlkreis VALUES(46, "Gifhorn - Peine", 9)
INSERT INTO Wahlkreis VALUES(47, "Hameln-Pyrmont - Holzminden", 9)
INSERT INTO Wahlkreis VALUES(48, "Hannover-Land II", 9)
INSERT INTO Wahlkreis VALUES(49, "Hildesheim", 9)
INSERT INTO Wahlkreis VALUES(50, "Salzgitter - Wolfenbüttel", 9)
INSERT INTO Wahlkreis VALUES(51, "Braunschweig", 9)
INSERT INTO Wahlkreis VALUES(52, "Helmstedt - Wolfsburg", 9)
INSERT INTO Wahlkreis VALUES(53, "Goslar - Northeim - Osterode", 9)
INSERT INTO Wahlkreis VALUES(54, "Göttingen", 9)
INSERT INTO Wahlkreis VALUES(55, "Bremen I", 5)
INSERT INTO Wahlkreis VALUES(56, "Bremen II - Bremerhaven", 5)
INSERT INTO Wahlkreis VALUES(57, "Prignitz - Ostprignitz-Ruppin - Havelland I", 4)
INSERT INTO Wahlkreis VALUES(58, "Uckermark - Barnim I", 4)
INSERT INTO Wahlkreis VALUES(59, "Oberhavel - Havelland II", 4)
INSERT INTO Wahlkreis VALUES(60, "Märkisch-Oderland - Barnim II", 4)
INSERT INTO Wahlkreis VALUES(61, "Brandenburg an der Havel - Potsdam-Mittelmark I - Havelland III - Teltow-Fläming I", 4)
INSERT INTO Wahlkreis VALUES(62, "Potsdam - Potsdam-Mittelmark II - Teltow-Fläming II", 4)
INSERT INTO Wahlkreis VALUES(63, "Dahme-Spreewald - Teltow-Fläming III - Oberspreewald-Lausitz I", 4)
INSERT INTO Wahlkreis VALUES(64, "Frankfurt (Oder) - Oder-Spree", 4)
INSERT INTO Wahlkreis VALUES(65, "Cottbus - Spree-Neiße", 4)
INSERT INTO Wahlkreis VALUES(66, "Elbe-Elster - Oberspreewald-Lausitz II", 4)
INSERT INTO Wahlkreis VALUES(67, "Altmark", 14)
INSERT INTO Wahlkreis VALUES(68, "Börde - Jerichower Land", 14)
INSERT INTO Wahlkreis VALUES(69, "Harz", 14)
INSERT INTO Wahlkreis VALUES(70, "Magdeburg", 14)
INSERT INTO Wahlkreis VALUES(71, "Dessau - Wittenberg", 14)
INSERT INTO Wahlkreis VALUES(72, "Anhalt", 14)
INSERT INTO Wahlkreis VALUES(73, "Halle", 14)
INSERT INTO Wahlkreis VALUES(74, "Burgenland - Saalekreis", 14)
INSERT INTO Wahlkreis VALUES(75, "Mansfeld", 14)
INSERT INTO Wahlkreis VALUES(76, "Berlin-Mitte", 3)
INSERT INTO Wahlkreis VALUES(77, "Berlin-Pankow", 3)
INSERT INTO Wahlkreis VALUES(78, "Berlin-Reinickendorf", 3)
INSERT INTO Wahlkreis VALUES(79, "Berlin-Spandau - Charlottenburg Nord", 3)
INSERT INTO Wahlkreis VALUES(80, "Berlin-Steglitz - Zehlendorf", 3)
INSERT INTO Wahlkreis VALUES(81, "Berlin-Charlottenburg - Wilmersdorf", 3)
INSERT INTO Wahlkreis VALUES(82, "Berlin-Tempelhof - Schöneberg", 3)
INSERT INTO Wahlkreis VALUES(83, "Berlin-Neukölln", 3)
INSERT INTO Wahlkreis VALUES(84, "Berlin-Friedrichshain - Kreuzberg - Prenzlauer Berg Ost", 3)
INSERT INTO Wahlkreis VALUES(85, "Berlin-Treptow - Köpenick", 3)
INSERT INTO Wahlkreis VALUES(86, "Berlin-Marzahn - Hellersdorf", 3)
INSERT INTO Wahlkreis VALUES(87, "Berlin-Lichtenberg", 3)
INSERT INTO Wahlkreis VALUES(88, "Aachen", 10)
INSERT INTO Wahlkreis VALUES(89, "Kreis Aachen", 10)
INSERT INTO Wahlkreis VALUES(90, "Heinsberg", 10)
INSERT INTO Wahlkreis VALUES(91, "Düren", 10)
INSERT INTO Wahlkreis VALUES(92, "Erftkreis I", 10)
INSERT INTO Wahlkreis VALUES(93, "Euskirchen - Erftkreis II", 10)
INSERT INTO Wahlkreis VALUES(94, "Köln I", 10)
INSERT INTO Wahlkreis VALUES(95, "Köln II", 10)
INSERT INTO Wahlkreis VALUES(96, "Köln III", 10)
INSERT INTO Wahlkreis VALUES(97, "Bonn", 10)
INSERT INTO Wahlkreis VALUES(98, "Rhein-Sieg-Kreis I", 10)
INSERT INTO Wahlkreis VALUES(99, "Rhein-Sieg-Kreis II", 10)
INSERT INTO Wahlkreis VALUES(100, "Oberbergischer Kreis", 10)
INSERT INTO Wahlkreis VALUES(101, "Rheinisch-Bergischer Kreis", 10)
INSERT INTO Wahlkreis VALUES(102, "Leverkusen - Köln IV", 10)
INSERT INTO Wahlkreis VALUES(103, "Wuppertal I", 10)
INSERT INTO Wahlkreis VALUES(104, "Solingen - Remscheid - Wuppertal II", 10)
INSERT INTO Wahlkreis VALUES(105, "Mettmann I", 10)
INSERT INTO Wahlkreis VALUES(106, "Mettmann II", 10)
INSERT INTO Wahlkreis VALUES(107, "Düsseldorf I", 10)
INSERT INTO Wahlkreis VALUES(108, "Düsseldorf II", 10)
INSERT INTO Wahlkreis VALUES(109, "Neuss I", 10)
INSERT INTO Wahlkreis VALUES(110, "Mönchengladbach", 10)
INSERT INTO Wahlkreis VALUES(111, "Krefeld I - Neuss II", 10)
INSERT INTO Wahlkreis VALUES(112, "Viersen", 10)
INSERT INTO Wahlkreis VALUES(113, "Kleve", 10)
INSERT INTO Wahlkreis VALUES(114, "Wesel I", 10)
INSERT INTO Wahlkreis VALUES(115, "Krefeld II - Wesel II", 10)
INSERT INTO Wahlkreis VALUES(116, "Duisburg I", 10)
INSERT INTO Wahlkreis VALUES(117, "Duisburg II", 10)
INSERT INTO Wahlkreis VALUES(118, "Oberhausen - Wesel III", 10)
INSERT INTO Wahlkreis VALUES(119, "Mülheim - Essen I", 10)
INSERT INTO Wahlkreis VALUES(120, "Essen II", 10)
INSERT INTO Wahlkreis VALUES(121, "Essen III", 10)
INSERT INTO Wahlkreis VALUES(122, "Recklinghausen I", 10)
INSERT INTO Wahlkreis VALUES(123, "Recklinghausen II", 10)
INSERT INTO Wahlkreis VALUES(124, "Gelsenkirchen", 10)
INSERT INTO Wahlkreis VALUES(125, "Steinfurt I - Borken I", 10)
INSERT INTO Wahlkreis VALUES(126, "Bottrop - Recklinghausen III", 10)
INSERT INTO Wahlkreis VALUES(127, "Borken II", 10)
INSERT INTO Wahlkreis VALUES(128, "Coesfeld - Steinfurt II", 10)
INSERT INTO Wahlkreis VALUES(129, "Steinfurt III", 10)
INSERT INTO Wahlkreis VALUES(130, "Münster", 10)
INSERT INTO Wahlkreis VALUES(131, "Warendorf", 10)
INSERT INTO Wahlkreis VALUES(132, "Gütersloh", 10)
INSERT INTO Wahlkreis VALUES(133, "Bielefeld", 10)
INSERT INTO Wahlkreis VALUES(134, "Herford - Minden-Lübbecke II", 10)
INSERT INTO Wahlkreis VALUES(135, "Minden-Lübbecke I", 10)
INSERT INTO Wahlkreis VALUES(136, "Lippe I", 10)
INSERT INTO Wahlkreis VALUES(137, "Höxter - Lippe II", 10)
INSERT INTO Wahlkreis VALUES(138, "Paderborn", 10)
INSERT INTO Wahlkreis VALUES(139, "Hagen - Ennepe-Ruhr-Kreis I", 10)
INSERT INTO Wahlkreis VALUES(140, "Ennepe-Ruhr-Kreis II", 10)
INSERT INTO Wahlkreis VALUES(141, "Bochum I", 10)
INSERT INTO Wahlkreis VALUES(142, "Herne - Bochum II", 10)
INSERT INTO Wahlkreis VALUES(143, "Dortmund I", 10)
INSERT INTO Wahlkreis VALUES(144, "Dortmund II", 10)
INSERT INTO Wahlkreis VALUES(145, "Unna I", 10)
INSERT INTO Wahlkreis VALUES(146, "Hamm - Unna II", 10)
INSERT INTO Wahlkreis VALUES(147, "Soest", 10)
INSERT INTO Wahlkreis VALUES(148, "Hochsauerlandkreis", 10)
INSERT INTO Wahlkreis VALUES(149, "Siegen-Wittgenstein", 10)
INSERT INTO Wahlkreis VALUES(150, "Olpe - Märkischer Kreis I", 10)
INSERT INTO Wahlkreis VALUES(151, "Märkischer Kreis II", 10)
INSERT INTO Wahlkreis VALUES(152, "Nordsachsen", 13)
INSERT INTO Wahlkreis VALUES(153, "Leipzig I", 13)
INSERT INTO Wahlkreis VALUES(154, "Leipzig II", 13)
INSERT INTO Wahlkreis VALUES(155, "Leipzig-Land", 13)
INSERT INTO Wahlkreis VALUES(156, "Meißen", 13)
INSERT INTO Wahlkreis VALUES(157, "Bautzen I", 13)
INSERT INTO Wahlkreis VALUES(158, "Görlitz", 13)
INSERT INTO Wahlkreis VALUES(159, "Sächsische Schweiz - Osterzgebirge", 13)
INSERT INTO Wahlkreis VALUES(160, "Dresden I", 13)
INSERT INTO Wahlkreis VALUES(161, "Dresden II - Bautzen II", 13)
INSERT INTO Wahlkreis VALUES(162, "Mittelsachsen", 13)
INSERT INTO Wahlkreis VALUES(163, "Chemnitz", 13)
INSERT INTO Wahlkreis VALUES(164, "Chemnitzer Umland - Erzgebirgskreis II", 13)
INSERT INTO Wahlkreis VALUES(165, "Erzgebirgskreis I", 13)
INSERT INTO Wahlkreis VALUES(166, "Zwickau", 13)
INSERT INTO Wahlkreis VALUES(167, "Vogtlandkreis", 13)
INSERT INTO Wahlkreis VALUES(168, "Waldeck", 7)
INSERT INTO Wahlkreis VALUES(169, "Kassel", 7)
INSERT INTO Wahlkreis VALUES(170, "Werra-Meißner - Hersfeld-Rotenburg", 7)
INSERT INTO Wahlkreis VALUES(171, "Schwalm-Eder", 7)
INSERT INTO Wahlkreis VALUES(172, "Marburg", 7)
INSERT INTO Wahlkreis VALUES(173, "Lahn-Dill", 7)
INSERT INTO Wahlkreis VALUES(174, "Gießen", 7)
INSERT INTO Wahlkreis VALUES(175, "Fulda", 7)
INSERT INTO Wahlkreis VALUES(176, "Hochtaunus", 7)
INSERT INTO Wahlkreis VALUES(177, "Wetterau", 7)
INSERT INTO Wahlkreis VALUES(178, "Rheingau-Taunus - Limburg", 7)
INSERT INTO Wahlkreis VALUES(179, "Wiesbaden", 7)
INSERT INTO Wahlkreis VALUES(180, "Hanau", 7)
INSERT INTO Wahlkreis VALUES(181, "Main-Taunus", 7)
INSERT INTO Wahlkreis VALUES(182, "Frankfurt am Main I", 7)
INSERT INTO Wahlkreis VALUES(183, "Frankfurt am Main II", 7)
INSERT INTO Wahlkreis VALUES(184, "Groß-Gerau", 7)
INSERT INTO Wahlkreis VALUES(185, "Offenbach", 7)
INSERT INTO Wahlkreis VALUES(186, "Darmstadt", 7)
INSERT INTO Wahlkreis VALUES(187, "Odenwald", 7)
INSERT INTO Wahlkreis VALUES(188, "Bergstraße", 7)
INSERT INTO Wahlkreis VALUES(189, "Eichsfeld - Nordhausen - Unstrut-Hainich-Kreis I", 16)
INSERT INTO Wahlkreis VALUES(190, "Eisenach - Wartburgkreis - Unstrut-Hainich-Kreis II", 16)
INSERT INTO Wahlkreis VALUES(191, "Kyffhäuserkreis - Sömmerda - Weimarer Land I", 16)
INSERT INTO Wahlkreis VALUES(192, "Gotha - Ilm-Kreis", 16)
INSERT INTO Wahlkreis VALUES(193, "Erfurt - Weimar - Weimarer Land II", 16)
INSERT INTO Wahlkreis VALUES(194, "Gera - Jena - Saale-Holzland-Kreis", 16)
INSERT INTO Wahlkreis VALUES(195, "Greiz - Altenburger Land", 16)
INSERT INTO Wahlkreis VALUES(196, "Sonneberg - Saalfeld-Rudolstadt - Saale-Orla-Kreis", 16)
INSERT INTO Wahlkreis VALUES(197, "Suhl - Schmalkalden-Meiningen - Hildburghausen", 16)
INSERT INTO Wahlkreis VALUES(198, "Neuwied", 11)
INSERT INTO Wahlkreis VALUES(199, "Ahrweiler", 11)
INSERT INTO Wahlkreis VALUES(200, "Koblenz", 11)
INSERT INTO Wahlkreis VALUES(201, "Mosel/Rhein-Hunsrück", 11)
INSERT INTO Wahlkreis VALUES(202, "Kreuznach", 11)
INSERT INTO Wahlkreis VALUES(203, "Bitburg", 11)
INSERT INTO Wahlkreis VALUES(204, "Trier", 11)
INSERT INTO Wahlkreis VALUES(205, "Montabaur", 11)
INSERT INTO Wahlkreis VALUES(206, "Mainz", 11)
INSERT INTO Wahlkreis VALUES(207, "Worms", 11)
INSERT INTO Wahlkreis VALUES(208, "Ludwigshafen/Frankenthal", 11)
INSERT INTO Wahlkreis VALUES(209, "Neustadt - Speyer", 11)
INSERT INTO Wahlkreis VALUES(210, "Kaiserslautern", 11)
INSERT INTO Wahlkreis VALUES(211, "Pirmasens", 11)
INSERT INTO Wahlkreis VALUES(212, "Südpfalz", 11)
INSERT INTO Wahlkreis VALUES(213, "Altötting", 2)
INSERT INTO Wahlkreis VALUES(214, "Erding - Ebersberg", 2)
INSERT INTO Wahlkreis VALUES(215, "Freising", 2)
INSERT INTO Wahlkreis VALUES(216, "Fürstenfeldbruck", 2)
INSERT INTO Wahlkreis VALUES(217, "Ingolstadt", 2)
INSERT INTO Wahlkreis VALUES(218, "München-Nord", 2)
INSERT INTO Wahlkreis VALUES(219, "München-Ost", 2)
INSERT INTO Wahlkreis VALUES(220, "München-Süd", 2)
INSERT INTO Wahlkreis VALUES(221, "München-West/Mitte", 2)
INSERT INTO Wahlkreis VALUES(222, "München-Land", 2)
INSERT INTO Wahlkreis VALUES(223, "Rosenheim", 2)
INSERT INTO Wahlkreis VALUES(224, "Starnberg", 2)
INSERT INTO Wahlkreis VALUES(225, "Traunstein", 2)
INSERT INTO Wahlkreis VALUES(226, "Weilheim", 2)
INSERT INTO Wahlkreis VALUES(227, "Deggendorf", 2)
INSERT INTO Wahlkreis VALUES(228, "Landshut", 2)
INSERT INTO Wahlkreis VALUES(229, "Passau", 2)
INSERT INTO Wahlkreis VALUES(230, "Rottal-Inn", 2)
INSERT INTO Wahlkreis VALUES(231, "Straubing", 2)
INSERT INTO Wahlkreis VALUES(232, "Amberg", 2)
INSERT INTO Wahlkreis VALUES(233, "Regensburg", 2)
INSERT INTO Wahlkreis VALUES(234, "Schwandorf", 2)
INSERT INTO Wahlkreis VALUES(235, "Weiden", 2)
INSERT INTO Wahlkreis VALUES(236, "Bamberg", 2)
INSERT INTO Wahlkreis VALUES(237, "Bayreuth", 2)
INSERT INTO Wahlkreis VALUES(238, "Coburg", 2)
INSERT INTO Wahlkreis VALUES(239, "Hof", 2)
INSERT INTO Wahlkreis VALUES(240, "Kulmbach", 2)
INSERT INTO Wahlkreis VALUES(241, "Ansbach", 2)
INSERT INTO Wahlkreis VALUES(242, "Erlangen", 2)
INSERT INTO Wahlkreis VALUES(243, "Fürth", 2)
INSERT INTO Wahlkreis VALUES(244, "Nürnberg-Nord", 2)
INSERT INTO Wahlkreis VALUES(245, "Nürnberg-Süd", 2)
INSERT INTO Wahlkreis VALUES(246, "Roth", 2)
INSERT INTO Wahlkreis VALUES(247, "Aschaffenburg", 2)
INSERT INTO Wahlkreis VALUES(248, "Bad Kissingen", 2)
INSERT INTO Wahlkreis VALUES(249, "Main-Spessart", 2)
INSERT INTO Wahlkreis VALUES(250, "Schweinfurt", 2)
INSERT INTO Wahlkreis VALUES(251, "Würzburg", 2)
INSERT INTO Wahlkreis VALUES(252, "Augsburg-Stadt", 2)
INSERT INTO Wahlkreis VALUES(253, "Augsburg-Land", 2)
INSERT INTO Wahlkreis VALUES(254, "Donau-Ries", 2)
INSERT INTO Wahlkreis VALUES(255, "Neu-Ulm", 2)
INSERT INTO Wahlkreis VALUES(256, "Oberallgäu", 2)
INSERT INTO Wahlkreis VALUES(257, "Ostallgäu", 2)
INSERT INTO Wahlkreis VALUES(258, "Stuttgart I", 1)
INSERT INTO Wahlkreis VALUES(259, "Stuttgart II", 1)
INSERT INTO Wahlkreis VALUES(260, "Böblingen", 1)
INSERT INTO Wahlkreis VALUES(261, "Esslingen", 1)
INSERT INTO Wahlkreis VALUES(262, "Nürtingen", 1)
INSERT INTO Wahlkreis VALUES(263, "Göppingen", 1)
INSERT INTO Wahlkreis VALUES(264, "Waiblingen", 1)
INSERT INTO Wahlkreis VALUES(265, "Ludwigsburg", 1)
INSERT INTO Wahlkreis VALUES(266, "Neckar-Zaber", 1)
INSERT INTO Wahlkreis VALUES(267, "Heilbronn", 1)
INSERT INTO Wahlkreis VALUES(268, "Schwäbisch Hall - Hohenlohe", 1)
INSERT INTO Wahlkreis VALUES(269, "Backnang - Schwäbisch Gmünd", 1)
INSERT INTO Wahlkreis VALUES(270, "Aalen - Heidenheim", 1)
INSERT INTO Wahlkreis VALUES(271, "Karlsruhe-Stadt", 1)
INSERT INTO Wahlkreis VALUES(272, "Karlsruhe-Land", 1)
INSERT INTO Wahlkreis VALUES(273, "Rastatt", 1)
INSERT INTO Wahlkreis VALUES(274, "Heidelberg", 1)
INSERT INTO Wahlkreis VALUES(275, "Mannheim", 1)
INSERT INTO Wahlkreis VALUES(276, "Odenwald - Tauber", 1)
INSERT INTO Wahlkreis VALUES(277, "Rhein-Neckar", 1)
INSERT INTO Wahlkreis VALUES(278, "Bruchsal - Schwetzingen", 1)
INSERT INTO Wahlkreis VALUES(279, "Pforzheim", 1)
INSERT INTO Wahlkreis VALUES(280, "Calw", 1)
INSERT INTO Wahlkreis VALUES(281, "Freiburg", 1)
INSERT INTO Wahlkreis VALUES(282, "Lörrach - Müllheim", 1)
INSERT INTO Wahlkreis VALUES(283, "Emmendingen - Lahr", 1)
INSERT INTO Wahlkreis VALUES(284, "Offenburg", 1)
INSERT INTO Wahlkreis VALUES(285, "Rottweil - Tuttlingen", 1)
INSERT INTO Wahlkreis VALUES(286, "Schwarzwald-Baar", 1)
INSERT INTO Wahlkreis VALUES(287, "Konstanz", 1)
INSERT INTO Wahlkreis VALUES(288, "Waldshut", 1)
INSERT INTO Wahlkreis VALUES(289, "Reutlingen", 1)
INSERT INTO Wahlkreis VALUES(290, "Tübingen", 1)
INSERT INTO Wahlkreis VALUES(291, "Ulm", 1)
INSERT INTO Wahlkreis VALUES(292, "Biberach", 1)
INSERT INTO Wahlkreis VALUES(293, "Bodensee", 1)
INSERT INTO Wahlkreis VALUES(294, "Ravensburg", 1)
INSERT INTO Wahlkreis VALUES(295, "Zollernalb - Sigmaringen", 1)
INSERT INTO Wahlkreis VALUES(296, "Saarbrücken", 12)
INSERT INTO Wahlkreis VALUES(297, "Saarlouis", 12)
INSERT INTO Wahlkreis VALUES(298, "St. Wendel", 12)
INSERT INTO Wahlkreis VALUES(299, "Homburg", 12)
